# -*- coding: utf-8 -*-
"""Prompt 模板 — 关键记忆抽取、任务状态、历史决策、记忆生成。"""

from app.prompts.key_fact_extraction import (
    KEY_FACT_SYSTEM_PROMPT,
    KEY_FACT_USER_TEMPLATE,
    KEY_FACT_OUTPUT_SCHEMA,
)
from app.prompts.task_state_extraction import (
    TASK_STATE_SYSTEM_PROMPT,
    TASK_STATE_USER_TEMPLATE,
    TASK_STATE_OUTPUT_SCHEMA,
)
from app.prompts.decision_extraction import (
    DECISION_SYSTEM_PROMPT,
    DECISION_USER_TEMPLATE,
    DECISION_OUTPUT_SCHEMA,
)
from app.prompts.memory_generation import (
    MEMORY_GENERATION_SYSTEM_PROMPT,
    MEMORY_GENERATION_USER_TEMPLATE,
    MEMORY_GENERATION_OUTPUT_SCHEMA,
)

__all__ = [
    "KEY_FACT_SYSTEM_PROMPT",
    "KEY_FACT_USER_TEMPLATE",
    "KEY_FACT_OUTPUT_SCHEMA",
    "TASK_STATE_SYSTEM_PROMPT",
    "TASK_STATE_USER_TEMPLATE",
    "TASK_STATE_OUTPUT_SCHEMA",
    "DECISION_SYSTEM_PROMPT",
    "DECISION_USER_TEMPLATE",
    "DECISION_OUTPUT_SCHEMA",
    "MEMORY_GENERATION_SYSTEM_PROMPT",
    "MEMORY_GENERATION_USER_TEMPLATE",
    "MEMORY_GENERATION_OUTPUT_SCHEMA",
]
