"""init_schema

Revision ID: 8b0794acafb6
Revises: 
Create Date: 2026-07-01 14:59:19.898898
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8b0794acafb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_agent',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('agent_name', sa.String(length=256), nullable=True),
    sa.Column('scene_id', sa.String(length=128), nullable=True),
    sa.Column('api_key_hash', sa.String(length=256), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('extra_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_agent_agent_id'), 't_agent', ['agent_id'], unique=True)
    op.create_index(op.f('ix_t_agent_scene_id'), 't_agent', ['scene_id'], unique=False)
    op.create_table('t_api_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('api_path', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_log_agent_path', 't_api_log', ['agent_id', 'api_path'], unique=False)
    op.create_index('idx_api_log_time', 't_api_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_t_api_log_agent_id'), 't_api_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_t_api_log_created_at'), 't_api_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_t_api_log_log_id'), 't_api_log', ['log_id'], unique=True)
    op.create_index(op.f('ix_t_api_log_trace_id'), 't_api_log', ['trace_id'], unique=False)
    op.create_table('t_interaction_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('scene_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interaction_processed', 't_interaction_record', ['processed', 'recorded_at'], unique=False)
    op.create_index('idx_interaction_session_turn', 't_interaction_record', ['session_id', 'turn_index'], unique=False)
    op.create_index('idx_interaction_user_time', 't_interaction_record', ['user_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_t_interaction_record_agent_id'), 't_interaction_record', ['agent_id'], unique=False)
    op.create_index(op.f('ix_t_interaction_record_record_id'), 't_interaction_record', ['record_id'], unique=True)
    op.create_index(op.f('ix_t_interaction_record_scene_id'), 't_interaction_record', ['scene_id'], unique=False)
    op.create_index(op.f('ix_t_interaction_record_session_id'), 't_interaction_record', ['session_id'], unique=False)
    op.create_index(op.f('ix_t_interaction_record_task_id'), 't_interaction_record', ['task_id'], unique=False)
    op.create_index(op.f('ix_t_interaction_record_user_id'), 't_interaction_record', ['user_id'], unique=False)
    op.create_table('t_memory',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('scene_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('memory_type', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decay_factor', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_record_ids', sa.JSON(), nullable=True),
    sa.Column('vector_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_session', 't_memory', ['session_id', 'status'], unique=False)
    op.create_index('idx_memory_status_time', 't_memory', ['status', 'created_at'], unique=False)
    op.create_index('idx_memory_task', 't_memory', ['task_id', 'status'], unique=False)
    op.create_index('idx_memory_user_type_status', 't_memory', ['user_id', 'memory_type', 'status'], unique=False)
    op.create_index(op.f('ix_t_memory_agent_id'), 't_memory', ['agent_id'], unique=False)
    op.create_index(op.f('ix_t_memory_memory_id'), 't_memory', ['memory_id'], unique=True)
    op.create_index(op.f('ix_t_memory_memory_type'), 't_memory', ['memory_type'], unique=False)
    op.create_index(op.f('ix_t_memory_scene_id'), 't_memory', ['scene_id'], unique=False)
    op.create_index(op.f('ix_t_memory_session_id'), 't_memory', ['session_id'], unique=False)
    op.create_index(op.f('ix_t_memory_status'), 't_memory', ['status'], unique=False)
    op.create_index(op.f('ix_t_memory_task_id'), 't_memory', ['task_id'], unique=False)
    op.create_index(op.f('ix_t_memory_user_id'), 't_memory', ['user_id'], unique=False)
    op.create_index(op.f('ix_t_memory_vector_id'), 't_memory', ['vector_id'], unique=False)
    op.create_table('t_memory_relation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_memory_id', sa.String(length=64), nullable=False),
    sa.Column('target_memory_id', sa.String(length=64), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mem_rel_source', 't_memory_relation', ['source_memory_id', 'relation_type'], unique=False)
    op.create_index('idx_mem_rel_target', 't_memory_relation', ['target_memory_id', 'relation_type'], unique=False)
    op.create_index(op.f('ix_t_memory_relation_source_memory_id'), 't_memory_relation', ['source_memory_id'], unique=False)
    op.create_index(op.f('ix_t_memory_relation_target_memory_id'), 't_memory_relation', ['target_memory_id'], unique=False)
    op.create_table('t_memory_vector',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('vector_store_id', sa.String(length=128), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vector_store_id')
    )
    op.create_index('idx_memory_vector_memory', 't_memory_vector', ['memory_id'], unique=False)
    op.create_index(op.f('ix_t_memory_vector_memory_id'), 't_memory_vector', ['memory_id'], unique=False)
    op.create_table('t_retrieval_request',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('scene_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('filter_conditions', sa.JSON(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('is_triggered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_retrieval_request_agent_id'), 't_retrieval_request', ['agent_id'], unique=False)
    op.create_index(op.f('ix_t_retrieval_request_request_id'), 't_retrieval_request', ['request_id'], unique=True)
    op.create_index(op.f('ix_t_retrieval_request_scene_id'), 't_retrieval_request', ['scene_id'], unique=False)
    op.create_index(op.f('ix_t_retrieval_request_session_id'), 't_retrieval_request', ['session_id'], unique=False)
    op.create_index(op.f('ix_t_retrieval_request_task_id'), 't_retrieval_request', ['task_id'], unique=False)
    op.create_index(op.f('ix_t_retrieval_request_user_id'), 't_retrieval_request', ['user_id'], unique=False)
    op.create_table('t_retrieval_result',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('keyword_score', sa.Float(), nullable=True),
    sa.Column('recency_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_result_request', 't_retrieval_result', ['request_id', 'rank'], unique=False)
    op.create_index(op.f('ix_t_retrieval_result_memory_id'), 't_retrieval_result', ['memory_id'], unique=False)
    op.create_index(op.f('ix_t_retrieval_result_request_id'), 't_retrieval_result', ['request_id'], unique=False)
    op.create_table('t_scene',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scene_id', sa.String(length=128), nullable=False),
    sa.Column('scene_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('extra_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_scene_scene_id'), 't_scene', ['scene_id'], unique=True)
    op.create_table('t_session',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('scene_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('extra_meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_session_agent_id'), 't_session', ['agent_id'], unique=False)
    op.create_index(op.f('ix_t_session_scene_id'), 't_session', ['scene_id'], unique=False)
    op.create_index(op.f('ix_t_session_session_id'), 't_session', ['session_id'], unique=True)
    op.create_index(op.f('ix_t_session_task_id'), 't_session', ['task_id'], unique=False)
    op.create_index(op.f('ix_t_session_user_id'), 't_session', ['user_id'], unique=False)
    op.create_table('t_task',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('scene_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('completed_items', sa.JSON(), nullable=True),
    sa.Column('pending_items', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_task_agent_id'), 't_task', ['agent_id'], unique=False)
    op.create_index(op.f('ix_t_task_scene_id'), 't_task', ['scene_id'], unique=False)
    op.create_index(op.f('ix_t_task_session_id'), 't_task', ['session_id'], unique=False)
    op.create_index(op.f('ix_t_task_task_id'), 't_task', ['task_id'], unique=True)
    op.create_index(op.f('ix_t_task_user_id'), 't_task', ['user_id'], unique=False)
    op.create_table('t_user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('extra_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_user_user_id'), 't_user', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_user_user_id'), table_name='t_user')
    op.drop_table('t_user')
    op.drop_index(op.f('ix_t_task_user_id'), table_name='t_task')
    op.drop_index(op.f('ix_t_task_task_id'), table_name='t_task')
    op.drop_index(op.f('ix_t_task_session_id'), table_name='t_task')
    op.drop_index(op.f('ix_t_task_scene_id'), table_name='t_task')
    op.drop_index(op.f('ix_t_task_agent_id'), table_name='t_task')
    op.drop_table('t_task')
    op.drop_index(op.f('ix_t_session_user_id'), table_name='t_session')
    op.drop_index(op.f('ix_t_session_task_id'), table_name='t_session')
    op.drop_index(op.f('ix_t_session_session_id'), table_name='t_session')
    op.drop_index(op.f('ix_t_session_scene_id'), table_name='t_session')
    op.drop_index(op.f('ix_t_session_agent_id'), table_name='t_session')
    op.drop_table('t_session')
    op.drop_index(op.f('ix_t_scene_scene_id'), table_name='t_scene')
    op.drop_table('t_scene')
    op.drop_index(op.f('ix_t_retrieval_result_request_id'), table_name='t_retrieval_result')
    op.drop_index(op.f('ix_t_retrieval_result_memory_id'), table_name='t_retrieval_result')
    op.drop_index('idx_result_request', table_name='t_retrieval_result')
    op.drop_table('t_retrieval_result')
    op.drop_index(op.f('ix_t_retrieval_request_user_id'), table_name='t_retrieval_request')
    op.drop_index(op.f('ix_t_retrieval_request_task_id'), table_name='t_retrieval_request')
    op.drop_index(op.f('ix_t_retrieval_request_session_id'), table_name='t_retrieval_request')
    op.drop_index(op.f('ix_t_retrieval_request_scene_id'), table_name='t_retrieval_request')
    op.drop_index(op.f('ix_t_retrieval_request_request_id'), table_name='t_retrieval_request')
    op.drop_index(op.f('ix_t_retrieval_request_agent_id'), table_name='t_retrieval_request')
    op.drop_table('t_retrieval_request')
    op.drop_index(op.f('ix_t_memory_vector_memory_id'), table_name='t_memory_vector')
    op.drop_index('idx_memory_vector_memory', table_name='t_memory_vector')
    op.drop_table('t_memory_vector')
    op.drop_index(op.f('ix_t_memory_relation_target_memory_id'), table_name='t_memory_relation')
    op.drop_index(op.f('ix_t_memory_relation_source_memory_id'), table_name='t_memory_relation')
    op.drop_index('idx_mem_rel_target', table_name='t_memory_relation')
    op.drop_index('idx_mem_rel_source', table_name='t_memory_relation')
    op.drop_table('t_memory_relation')
    op.drop_index(op.f('ix_t_memory_vector_id'), table_name='t_memory')
    op.drop_index(op.f('ix_t_memory_user_id'), table_name='t_memory')
    op.drop_index(op.f('ix_t_memory_task_id'), table_name='t_memory')
    op.drop_index(op.f('ix_t_memory_status'), table_name='t_memory')
    op.drop_index(op.f('ix_t_memory_session_id'), table_name='t_memory')
    op.drop_index(op.f('ix_t_memory_scene_id'), table_name='t_memory')
    op.drop_index(op.f('ix_t_memory_memory_type'), table_name='t_memory')
    op.drop_index(op.f('ix_t_memory_memory_id'), table_name='t_memory')
    op.drop_index(op.f('ix_t_memory_agent_id'), table_name='t_memory')
    op.drop_index('idx_memory_user_type_status', table_name='t_memory')
    op.drop_index('idx_memory_task', table_name='t_memory')
    op.drop_index('idx_memory_status_time', table_name='t_memory')
    op.drop_index('idx_memory_session', table_name='t_memory')
    op.drop_table('t_memory')
    op.drop_index(op.f('ix_t_interaction_record_user_id'), table_name='t_interaction_record')
    op.drop_index(op.f('ix_t_interaction_record_task_id'), table_name='t_interaction_record')
    op.drop_index(op.f('ix_t_interaction_record_session_id'), table_name='t_interaction_record')
    op.drop_index(op.f('ix_t_interaction_record_scene_id'), table_name='t_interaction_record')
    op.drop_index(op.f('ix_t_interaction_record_record_id'), table_name='t_interaction_record')
    op.drop_index(op.f('ix_t_interaction_record_agent_id'), table_name='t_interaction_record')
    op.drop_index('idx_interaction_user_time', table_name='t_interaction_record')
    op.drop_index('idx_interaction_session_turn', table_name='t_interaction_record')
    op.drop_index('idx_interaction_processed', table_name='t_interaction_record')
    op.drop_table('t_interaction_record')
    op.drop_index(op.f('ix_t_api_log_trace_id'), table_name='t_api_log')
    op.drop_index(op.f('ix_t_api_log_log_id'), table_name='t_api_log')
    op.drop_index(op.f('ix_t_api_log_created_at'), table_name='t_api_log')
    op.drop_index(op.f('ix_t_api_log_agent_id'), table_name='t_api_log')
    op.drop_index('idx_api_log_time', table_name='t_api_log')
    op.drop_index('idx_api_log_agent_path', table_name='t_api_log')
    op.drop_table('t_api_log')
    op.drop_index(op.f('ix_t_agent_scene_id'), table_name='t_agent')
    op.drop_index(op.f('ix_t_agent_agent_id'), table_name='t_agent')
    op.drop_table('t_agent')
    # ### end Alembic commands ###
