"""add_status_column_and_indexes

Revision ID: 9d20e9cb00e2
Revises: 52c1d1f2e3a4
Create Date: 2026-07-14 12:18:21.244848
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9d20e9cb00e2'
down_revision: Union[str, None] = '52c1d1f2e3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_interaction_record', 'interaction_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               comment=None,
               existing_comment='交互类型: dialogue / session / task_process')
    op.alter_column('t_interaction_record', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_comment='记录状态: pending_extract / processed / failed')
    op.create_index('idx_interaction_type_user', 't_interaction_record', ['interaction_type', 'user_id'], unique=False)
    op.create_index(op.f('ix_t_interaction_record_interaction_type'), 't_interaction_record', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_t_interaction_record_status'), 't_interaction_record', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_interaction_record_status'), table_name='t_interaction_record')
    op.drop_index(op.f('ix_t_interaction_record_interaction_type'), table_name='t_interaction_record')
    op.drop_index('idx_interaction_type_user', table_name='t_interaction_record')
    op.alter_column('t_interaction_record', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_comment='记录状态: pending_extract / processed / failed')
    op.alter_column('t_interaction_record', 'interaction_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               comment='交互类型: dialogue / session / task_process')
    # ### end Alembic commands ###
