"""init_schema

Revision ID: fe65c848d7d5
Revises: 8b0794acafb6
Create Date: 2026-07-03 15:18:18.742112
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fe65c848d7d5'
down_revision: Union[str, None] = '8b0794acafb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
